In [2]:
import numpy as np
list = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list)

In [7]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Solution:
Yes, list is of 'List' type and array_list is of 'array' type.
'''
type(list)

list

In [8]:
type(array_list)

array([1, 2, 3, 4, 5])

In [12]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.
Solution:
'''
for i in list:
    print(type(i))
    
for j in array_list:
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [20]:
'''Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Solution:
No, This satement will copy the elements from list and create a array then it will paste it into 'array_list'
'''
array_list = np.array(object = list, dtype = int)
print(array_list)
print(type(array_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [24]:
'''Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
Solution:
'''
np.shape(num_array)

(2, 3)

In [25]:
np.size(num_array)

6

In [28]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
Solution:
'''
numpy_array = np.zeros([3,3])
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
Solution:
'''
import
id_matrix = np.eye([5,5])
id_matrix

TypeError: 'list' object cannot be interpreted as an integer